### PR TITLE
Issue 105

### LINKED ISSUE #105: Codify doesn't deal well with unknown resource types
I tried running `naml codify` on an `ObjectBucketClaim` resource:

```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: example-obc
spec:
  generateBucketName: example-obc
  storageClassName: openshift-storage.noobaa.io
```

I was expecting it to fail due to an unknown resource type, but to my surprise it didn't emit any errors. The resulting `main.go` has no resources (and does not compile).

It would be nice if `naml codify` would emit an error (and fail) when it is unable to successfully convert the input.

### PR DESCRIPTION
**Pull request by kris-nova**
Addressing concerns in 105

closes #105

### CODE REVIEW

File: cmd.go [hunk 1]
```diff
@@ -306,6 +307,12 @@ func RunCommandLineWithOptions() error {
 
 					cbytes, err := Codify(os.Stdin, codifyValues)
 					if err != nil {
+						if len(cbytes) > 0 {
+							// We have both
+							fmt.Println(string(cbytes))
+							fmt.Fprintf(os.Stderr, "\nWARNING ⚠\n\nUnable to parse full system: %v\n\nWARNING ⚠\n", err.Error())
```
Comment (larsks) [inline cmd.go:313]: I thought this should go [here](https://github.com/kris-nova/naml/blob/main/codify.go#L380) so the error message can be explicit about the Kind that couldn't be converted. That sort of specificity in error messages is helpful.
